### ISSUE TITLE
Font names in TTF/OTF Files

### ISSUE THREAD

**Issue by RedTiger26** [indestructible-type/Jost#11]
There is some mixup with the font names in the TTF/OTF files:

- Renner Thin is just called Renner (italic is okay)
- Renner Book is just called Renner* (italic also wrong)
- Renner Semi is just called Renner* (italic also wrong)
- Renner Bold is just called Renner* (italic also wrong)

This makes it impossible to use the fonts correctly in software that is not using specific font handling, like MS Word.

For additional usability it would be great to include the numbering in the font names, so sorting would be correct.

**Comment by randybruder** [comment]
Having the same issue. For reference, here's a quick screen recording of how they appear in Illustrator:

https://youtu.be/f5qL-sLbNmg

**Comment by EwonRael** [comment]
Ug it's embarrassing to still be having metadata issues. There's also a difference in some of the metrics that needs to be fixed. I'll get on this asap.

**Comment by EwonRael** [comment]
Okay folks! I think I got most of the metadata issues sorted out. It appears FontForge keeps changing my metadata, the weirdest example of this is that it keeps changing "Semi" to "Demi".

Fingers crossed.

The fact that Renner* Book and Bold both appear as "Renner*" on older programs is actually to help with usability in non specific font handling programs. If you want to use the bold weight just use the in-program bold formatting on Renner*. If I didn't do this than when you use the in-program bold formatting on Renner*, it would do its own ugly auto bold and not use the bold font. This would be especially useless in instances where one is copying large amounts of text with formatting.

I'm not going to close this issue because I like the idea of including the numbering system into the font naming for ease-of-use, but that's a bigger time investment than I can commit to right this second. The good news is that I've (hopefully!) fixed the big issues with the naming conventions.

**Comment by randybruder** [comment]
I just downloaded the new version and it works flawlessly (in Illustrator, that's all I tested it in.) Thanks for fixing the metadata!

**Comment by EwonRael** [comment]
Just released the latest version that not only includes the basic meta data fix, but now should also have the numbering in the font names, depending on what program you are using and what that program supports.

Hope that help!
