### ISSUE TITLE
Center and curvature of bold and heavy s

### ISSUE THREAD

**Issue by kslstn** [indestructible-type/Jost#13]
When comparing Renner* with Avenir Next, I noticed the center of the bold and heavy **s** look squeezed. The concave curves of the s also seem to have some tension; like the negative space are tiny balloons trying to squeeze the s into something thinner. The result is in my opinion a letter that looks less geometric than the rest of the bold and heavy fonts.

Otherwise, I love this typeface. Thank you.

**Comment by EwonRael** [comment]
Thanks!

The Black version of Renner* is bolder than the heaviest version of Avenir Next. Some of these issues relating to the "s" letterform are because of this fact.

That being said I do think there are some general issues relating to the "s" in bolder weights, especially when interpolating between them. 

I will do my best to rework the "s" in the heavier weights. I would ultimately like to make the least number of compromises possible. I can't promise that woln't include an "s" that looks a tad squeezed, but I can get back to you when I make the next release.

Hope that helps!

**Comment by EwonRael** [comment]
I looked into this and redrew the "s" at the bolder weights for the latest release. 

There's no magic solution, but I do this the bolder "s" design was something worth revisiting. I hope you like the new one.


![drawing](https://user-images.githubusercontent.com/16858124/43984413-4f8a6d36-9cb5-11e8-8ae2-70d5158330c3.png)
