### ISSUE TITLE
Macron on vowel increases character size.

### ISSUE THREAD

**Issue by Aoterra** [indestructible-type/Jost#15]
Hi there,
Love the font, but I have a concern. From time to time I need to write text that includes Maōri words. When I add a macron (the line over the ō), to Renner*, the character size increases for that letter, and kerning looks wrong. What am I doing wrong?
Thanks

**Comment by EwonRael** [comment]
I'll look into this. It's likely that this is an issue with Renner* and not you. I'm looking on addressing a lot of things for the 3.3 release, so this will be one of them.

**Comment by Aoterra** [comment]
Awesome, I’ll look forward to the new release!

David Laing
Sustained Consulting
Ph: 021 609 028

**Comment by Aoterra** [comment]
Hi there,
I also had trouble replicating it in desktop applications.  Then I remembered where I could consistently make the issue happen, which is on the font website: (http://indestructibletype.com/Renner). In the section which is editable "Test Renner* out", type the word "Maōri" and you will see the issue clearly. Perhaps it only happens there?

**Comment by EwonRael** [comment]
Yeah so in order to make web pages load faster the web versions of the font include a reduced character set because then the page has to load less data in order to display the text.

The reduced character set of Renner* doesn't include the ō right now, so what's happening is that your web browser is replacing Renner* with another font that does include a ō.

In the next update I will have the web version include a full character set because honestly, in this day and age, it doesn't make enough of a difference.

I hope that helps to explain the issue.

**Comment by Aoterra** [comment]
Yes, that's all good, thanks for the update, I appreciate knowing why it happened.

**Comment by EwonRael** [comment]
Okay so not that this is that big of a deal, but I just updating the website so that this issue would stop happening. Now the ō should render correctly on the website too.
