### ISSUE TITLE
Font Not Visible in PDF

### ISSUE THREAD

**Issue by walnuttea** [indestructible-type/Jost#24]
Having trouble with Jost and PDFs. Anytime a file containing Jost is exported, the font does not show up on any computer that does not have it locally installed.

**Comment by pratikborsadiya** [comment]
This seems to be an issue with the PDF creator rather then font. Which software are you using to create PDF files?

**Comment by walnuttea** [comment]
Can confirm this is not an issue with the previous version of the font, "Renner" - so this issue is probably something that popped up post update!

**Comment by pratikborsadiya** [comment]
Try the attached PDF file it has latest version of Jost embedded with it. If this doesn't work fine then attach a sample PDF file you've generated. 
[Document1.pdf](https://github.com/indestructible-type/Jost/files/2334502/Document1.pdf)

**Comment by walnuttea** [comment]
Interesting, your PDF is working just fine. I'm going to attach the two PDFs I used.
[JostSample.pdf](https://github.com/indestructible-type/Jost/files/2334513/JostSample.pdf)
[JostTrial.pdf](https://github.com/indestructible-type/Jost/files/2334517/JostTrial.pdf)

**Comment by pratikborsadiya** [comment]
It's exactly what I expected. Somehow keynote is not able to embed the font with PDF file that's why the PDF reader on other machine will substitute Jost with other locally installed font. Here are the screenshots which confirms the same.

What is interesting though is that even if i have Jost installed on my computer the PDF reader on my computer substituted it with other font. 

![screenshot from 2018-08-30 09-26-45](https://user-images.githubusercontent.com/7806891/44828892-9a7f1a80-ac37-11e8-9d78-25e222b33401.png)
![screenshot from 2018-08-30 09-27-14](https://user-images.githubusercontent.com/7806891/44828893-9b17b100-ac37-11e8-8890-b9e2768585e6.png)
![screenshot from 2018-08-30 09-27-34](https://user-images.githubusercontent.com/7806891/44828894-9b17b100-ac37-11e8-910c-8ef55c0ff68e.png)

**Comment by walnuttea** [comment]
That is interesting. Here's the rendering on another machine (happens to be a Windows machine):
![brokenjost](https://user-images.githubusercontent.com/38009629/44829202-15691680-abe1-11e8-8d1a-e22974dc1646.jpg)

It's not just Keynote, but Sketch is causing the same issue. How does this render for you?

[renner.pdf](https://github.com/indestructible-type/Jost/files/2334557/renner.pdf)

**Comment by walnuttea** [comment]
thanks for testing that out. looks like something changed in the latest update. The old Renner version seems to be rendering fine for both you and me on other machines.

**Comment by EwonRael** [comment]
Hey!

This looks like a meta data issue, which this font has been plagued with sense day one. 

Older version of the font were exported using FontForge. This resulted in a whole host of issues [(example a)](https://github.com/indestructible-type/Jost/issues/16), [(example b)](https://github.com/indestructible-type/Jost/issues/11).

I have sense switched to TruFont as my program of choice to export the font files, as this program doesn't seem to randomly drop meta data. 

This would be the most significant change, and likely the culprit. I'm going to take some time to compare the meta data and see if I can't isolate the problem.

Unfortunately, I can't seem to reproduce this issue, so I'm going to be trouble shooting based mostly off of guesses.

Thanks for your help and I will get back to you!

**Comment by walnuttea** [comment]
Thanks for the followup Owen. Let me know if I can help in re creating the issue. Hopefully it's an easy fix :) I'll stick to the older version of the font until then, but please do let me know once it's good to go.

**Comment by EwonRael** [comment]
I think I may have found the culprit, and I need your help testing something...

This is only an issue in the OTF version of the font, correct? 

My work flow right now outputs the TTF versions first, then converts those files to OTF. I think this is causing all sorts of issues, including this one. 

I'm looking into alternative conversion methods, but if this really is the root cause I may end up dropping the inclusion of OTF versions.  

:(

**Comment by walnuttea** [comment]
Looks like you found the issue! Seems to be an issue with OTF only - the TTF version works fine. Might be worth dropping the OTF version for now, but hopefully it can be reintroduced in the very near future once you find an alternative conversion method :)

**Comment by EwonRael** [comment]
Okay!

I think I got this fixed for both the ttf and otf versions in the latest release! 

Thanks for your help!
