### ISSUE TITLE
Use of italic axis instead of the slant axis

### ISSUE THREAD

**Issue by glyphe** [indestructible-type/Jost#25]
Why do you use the italic axis and not the slant axis, since the letter shapes aren’t true italics? Some variable fonts on v-fonts.com use the italic (Meta for example, but there it’s a true italic and there is no gradation between italic and upright) others the slant axis (like Output Sans). Does this have any technical reasons? If not I find it a bit confusing since it seems to be slanted and not a true italic.

**Comment by EwonRael** [comment]
I do not have a specific technical reason for using the italic axis.

The letters are optically compensated in the italic version meaning there are some geometric differences as it is not just a simple slant transformation. It could be argued that the optical corrections make the italic version of the font a "true" italic. This is the language that designer [Mark Simonson](https://www.marksimonson.com/notebook/view/FakevsTrueItalics), creator of Proxima Nova, uses. Whether or not this is because he is writing to laymen I can't say, but I do think the move is not without some precedent. 

However, I do understand the argument that the italic version is more of a oblique than italic because there is no real change to the letter-forms.

Unlike static fonts, this is a new technology, and a lot of these conventions have yet to be codified. I recognize that as a designer I have a role in establishing these conventions. I want there to be conversation surrounding it, because I don't want to end up with stupid conventions.

This is not a decision I made without some consideration. My two main arguments for the axis naming is the use of optical compensation, and the fact that the majority of people who use fonts don't understand or recognize the difference between an italic and oblique. The distinction between you and me is meaningful (but also has grey area), but to force regular users of a font to adopt that esoteric language distinction feels pedantic.

I do want this to be a conversation, though. I'm open to changing it if I think it's the right thing to do.

**Comment by davelab6** [comment]
https://www.w3.org/TR/css-fonts-4/ says "For the purposes of font matching,
User Agents may treat italic as a synonym for oblique." so I am not sure it
matters too much. However, slnt may be better because it allows users to
set the angle via font-style in an easy way

**Comment by uncinarynin** [comment]
Jost* Italic uses the single-level "a" by default, I noticed. (Which makes a lot of sense because this letterform originally came from Italics.)

**Comment by EwonRael** [comment]
I'm closing this issue for the time being.
