### ISSUE TITLE
Capital Sharp S: ẞ

### ISSUE THREAD

**Issue by Florian1990** [indestructible-type/Jost#26]
I noticed that Jost* does not feature a proper capital sharp s (ẞ, just like Segoe UI on GitHub). A good entry point for designing the capital sharp s can be found on [typography.guru](https://typography.guru/journal/capital-sharp-s-designs/).

**Comment by EwonRael** [comment]
Hello.

When you say that it does not feature a proper capital sharp s do you mean that something about the existing sharp s is improper, or that Jost* is for some reason acting for you like it doesn't even have a sharp s?

I am quite confident that Jost* has a capital sharp s because when I copy the sharp s from your comment and paste it into the "Try me out!" section of the page of Jost* it renders. I have attached a screen shot.
![screenshot_20180909-160619 2](https://user-images.githubusercontent.com/16858124/45269439-b1014f00-b44b-11e8-834c-68ab1a946a04.png)

**Comment by Florian1990** [comment]
Sorry for being imprecise. There definitely is a glyph for the capital sharp s, but the design is basically the design for the small letter. For details about how to design, you can start with the article above. There are more detailed resources, but many of them are in German.

**Comment by EwonRael** [comment]
So when this [originally came up](https://github.com/indestructible-type/Jost/issues/10) I was linked to an [article on Typography.Guru](https://typography.guru/journal/the-capital-%C3%9F-design-can-we-create-an-uppercase-character-from-lowercase-r59/) about the capital sharp S.

> Visual similarities between a Latin uppercase letter and its lowercase counterpart aren’t a flaw—they are perfectly normal. Some character pairs (like S/s, as well as ones based on ligatures such as W/w) are very similar, others less so. But either way—it’s not a criteria for good or bad letter designs.

That's the article that I read before designing the capital sharp S. It is my current understanding that this is more a matter of taste than anything else. That being said I am not a German speaker, and so my opinion is based only off of what I have read and not personal experience. 

I'm going to leave it for the time being. I'm open to changing that and may consult some of my peers on this matter, so I'm leaving this issue open.

**Comment by soc** [comment]
Hi @EwonRael,

maybe this article provides some additional details: https://typography.guru/journal/capital-sharp-s-designs/ (search for "A rounded top right segment").

Cheers,
Simon

**Comment by EwonRael** [comment]
@soc silly billy that is the article linked to in the very first comment

**Comment by soc** [comment]
Weird, I followed the link and was convinced it was a different article.
I apologize for the noise.
