### ISSUE TITLE
Cyrillic alphabet

### ISSUE THREAD

**Issue by kosiakk** [indestructible-type/Jost#9]
I know, that's a stretch for a free font, but maybe there's a chance of Cyrillic alphabet? 
Range [U+0410 — U+044F](https://unicode-table.com/en/blocks/cyrillic/) is required for Russian language. Maybe [Ivan Gladkikh](http://jovanny.ru/) could help you with that part.

**Comment by EwonRael** [comment]
I've been weary of supporting languages that I don't speak because I'm hardly familiar enough with the letters to know when the designs are legible or not. That being said I would love to collaborate and will send Ivan Gladkikh an email and see what happens.

**Comment by EwonRael** [comment]
Hey everyone!

I just added the Cyrillic alphabet. I expect that there will be some issues with this because I don't speak the language. I have reached out to a few Russian speaking friends and they gave the go-head, but I don't think they're as design minded as some folks here who might see issues I missed.

All that being said I'm going to go ahead and close this one out. If there are issues with the Cyrillic alphabet please open a new bug report with that specific issue.
